// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL5fRJ1s0XIL3CIBdIdVGxURA9mRyIQKQ',
    appId: '1:927029456514:web:aeac8f650b752b36014e9b',
    messagingSenderId: '927029456514',
    projectId: 'tasklist-df910',
    authDomain: 'tasklist-df910.firebaseapp.com',
    storageBucket: 'tasklist-df910.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQW3PVK4bB5qFiNnwFMuJiBWXIcTChVtQ',
    appId: '1:927029456514:android:f62ad754ab307516014e9b',
    messagingSenderId: '927029456514',
    projectId: 'tasklist-df910',
    storageBucket: 'tasklist-df910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ95H6UMSij-432-7WZHzZ2WNoJuwDtEs',
    appId: '1:927029456514:ios:c3b057aaac8f6d38014e9b',
    messagingSenderId: '927029456514',
    projectId: 'tasklist-df910',
    storageBucket: 'tasklist-df910.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ95H6UMSij-432-7WZHzZ2WNoJuwDtEs',
    appId: '1:927029456514:ios:c3b057aaac8f6d38014e9b',
    messagingSenderId: '927029456514',
    projectId: 'tasklist-df910',
    storageBucket: 'tasklist-df910.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL5fRJ1s0XIL3CIBdIdVGxURA9mRyIQKQ',
    appId: '1:927029456514:web:5d57970ddfcbe331014e9b',
    messagingSenderId: '927029456514',
    projectId: 'tasklist-df910',
    authDomain: 'tasklist-df910.firebaseapp.com',
    storageBucket: 'tasklist-df910.firebasestorage.app',
  );
}
